title: Jerome Wendoh Milimu,PhD
description: Jerome is a clinical researcher turned Public Health specialist. he has over the last decade worked on a number of exciting projects including, Malaria, The human microbiome, TB & HIV. His current intrests are the application of data analytics in tackling Global Health challenges.
LinkedIn_username: Jerome Wendoh Milimu
github_username: Jerome Wendoh Milimu
theme: jekyll-theme-cayman
